#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [ $SPIN ]; then
  sudo add-apt-repository -y ppa:aos1/diff-so-fancy

  sudo apt-get update

  sudo apt-get install -y diff-so-fancy
  sudo apt-get install -y ripgrep
  sudo apt-get install -y fd-find

  sudo ln -sf $(which fdfind) /usr/local/bin/fd

  # Neovim
  sudo apt-get -y install ninja-build gettext libtool libtool-bin automake cmake g++ pkg-config unzip curl doxygen
  git clone https://github.com/neovim/neovim ~/.neovim
  cd ~/.neovim && make
  sudo make install
fi

